name: Run Translator

on:
    workflow_dispatch: 
     inputs:
       text:
         description: 'Text to translate'
         required: true
         default: 'Hello, how are you?'

jobs:
  run-translator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python main.py "${{ github.event.inputs.text }}"
