name: Run Translator

on:
    workflow_dispatch:
      inputs:
        text:
          description: 'Text to translate'
          required: true
          default: 'Hello, how are you?'
    issue_comment:
      types: [created]

jobs:
  run-translator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run main.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            # Extract comment body and issue title using GitHub CLI
            gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} | jq -r '.title' > issue_title.txt
            gh api repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }} | jq -r '.body' > comment_body.txt
            issue_title=$(cat issue_title.txt)
            comment_body=$(cat comment_body.txt)
            # Only run if issue title matches translation template
            if [[ "$issue_title" == Translation:* ]]; then
              python main.py "$comment_body"
            fi
          else
            python main.py "${{ github.event.inputs.text }}"
          fi
